version: '3.0'
services:
  valhalla:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # The tile_file must be located in the Dockerfile folder.
        # The tile_file has priority and is used when valid.
        # If the tile_file doesn't exist, the url is used instead.
        # Don't blank out tile_url when you use tile_file and vice versa.
        tile_file: kanto-latest.osm.pbf
        tile_url: https://download.geofabrik.de/asia/japan/kanto-latest.osm.pbf
        # Get correct bounding box from e.g. https://boundingbox.klokantech.com/
        min_x: 0 # 18 # -> Albania | -180 -> World
        min_y: 0 # 38 # -> Albania | -90  -> World
        max_x: 0 # 22 # -> Albania |  180 -> World
        max_y: 0 # 43 # -> Albania |  90  -> World
    ports:
      - "8002:8002"
